# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: bind-wrapper-report

on:
  push:  # 为了调试方便，修改代码之后push上去即可以看到效果
    paths: # 指定只有哪些文件修改了才会触发该工作流程
      - main.go
      - .github/workflows/bind-wrapper-report.yml
  schedule: # 定时任务
    - cron: "0 0 * * *" # 每天 0 点跑 => 东八区 8点
jobs:

  bind-wrapper-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.2'
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - run: go mod tidy
    - name: Build and run Go code
      run: |
        go build -o crawler ./main.go
        ./crawler

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Added files"
        git push
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
